In [50]:
import sys
import pandas as pd
import numpy as np
sys.path.append(r"D:\_1_Technicals\DataScience_Bootcamp\Final_project\Flutter_ArduinoConnect")
import common_functions as cf
from sklearn.preprocessing import StandardScaler

In [51]:
df = pd.read_csv(r"D:\_1_Technicals\DataScience_Bootcamp\Final_project\Flutter_ArduinoConnect\00_DataSets\1_3\t_stand_front_drinksmallcup_10ml_1s_right.csv")

In [52]:
df=df.iloc[0:100]

In [53]:
df.columns= ["time","rotR_x","rotR_y","rotR_z","acc_x","acc_y","acc_z","or_x","or_y","or_z","grav_x","grav_y","grav_z"]

# # fix units
df.acc_x = df.acc_x/4096.0
df.acc_y = df.acc_y/4096.0
df.acc_z = df.acc_z/4096.0

df.rotR_x = df.rotR_x/16.4
df.rotR_y = df.rotR_y/16.4
df.rotR_z = df.rotR_z/16.4

df.grav_x = df.grav_x/4096.0
df.grav_y = df.grav_y/4096.0
df.grav_z = df.grav_z/4096.0
df = df.drop(columns="time").reset_index().rename(columns={"index":"time"}).set_index("time")

#Basic features
df.insert(0, 'accel_x', df.acc_x + df.grav_x)
df.insert(1, 'accel_y', df.acc_y + df.grav_y)
df.insert(2, 'accel_z', df.acc_z + df.grav_z)
df.insert(3, 'accel_norm', np.sqrt(df.accel_x**2 + df.accel_y**2 + df.accel_z**2))
df = df.drop(['accel_x', 'accel_y', 'accel_z'], axis=1)


std = StandardScaler().set_output(transform='pandas')
df = std.fit_transform(df)
np.asarray(df).reshape(4,25,13)

In [54]:
df

,rotR_x,rotR_y,rotR_z,acc_x,acc_y,acc_z,or_x,or_y,or_z,grav_x,grav_y,grav_z
time,,,,,,,,,,,,
0,-1.402439,3.963415,3.536585,0.003662,0.033691,0.030273,78,21,211,0.979736,-0.071045,0.186523
1,-31.341463,6.585366,7.256098,0.008057,0.058105,0.051514,77,22,211,0.978271,-0.078613,0.191406
2,-82.256098,26.829268,15.426829,0.023682,0.223877,0.046875,76,26,213,0.973877,-0.099121,0.203613
3,-128.170732,32.560976,25.243902,0.071533,0.037598,0.085693,74,34,218,0.964111,-0.150879,0.218018
4,-159.878049,47.804878,33.902439,0.066650,0.092773,0.107910,71,42,224,0.949707,-0.210449,0.231201
...,...,...,...,...,...,...,...,...,...,...,...,...
95,18.902439,-40.365854,94.390244,-0.078613,-0.108643,0.007812,-2,86,119,-0.040283,-0.997803,0.051514
96,39.085366,-37.865854,98.231707,-0.094238,-0.145264,0.060303,-4,86,115,-0.081787,-0.994385,0.065186
97,51.768293,-29.146341,109.207317,-0.097656,0.029053,0.036621,-9,83,109,-0.171875,-0.978271,0.113281
98,57.195122,-30.731707,108.719512,-0.086182,0.018311,0.038086,-12,81,106,-0.211914,-0.967529,0.136719
99,69.024390,-30.243902,111.158537,-0.068848,0.098389,0.011719,-14,79,103,-0.256592,-0.951904,0.166748

(100, 13)